### ISSUE TITLE
Added sections to acknowledgements

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/XML-mapping#63]
91c871f5eacf5c48bbbf6a31b240ac5a099a9aa3

This was requested by Exeter for the kitchen sink as it came up recently. Please confirm the tagging I added is OK with you!

Cheers
M

**Comment by gnott** [comment]
I've tried parsing this as it is, and when I do then by default the parser is also picking up the section tags and the section id values. This won't be allowed though because acknowledgements is only allowed to have paragraphs in it, and not sections.

The two possible options here are
a) allow sections in acknowledgements, for which we'd need to update the article schema to allow it
b) I change the parser so if it finds sections, then to throw away the id and the section and to only keep the paragraphs

**Comment by Melissa37** [comment]
I'd go with:
a) allow sections in acknowledgements, for which we'd need to update the article schema to allow it

@thewilkybarkid ?
