### ISSUE TITLE
Added new appendix with no sections

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/XML-mapping#64]
8e6cc2dc7c567f71f7dfde38116311e77ef28690

**Comment by gnott** [comment]
The content in Appendix 3 here is ignored by the parser right now, because it is only picking up sections inside app tags.

I think (@thewilkybarkid can correct me if I'm wrong) in the JSON schema each appendix content must conform to the body schema definition, and a body must contain only sections. If that is true, then we'll need to get the parser to wrap this in a section anyway, and for that it will need an id and a title for the section (which we will have to create out what is available).

Is it a must have - an app with no sec ?

**Comment by thewilkybarkid** [comment]
There's already an open PR for the JSON Schema to make it so appendices don't have to contain sections - https://github.com/elifesciences/api-raml/pull/115.

**Comment by gnott** [comment]
This should be supported by the latest parser version now, it has a test specifically for this and I believe it passes validation too.
