### ISSUE TITLE
Is MathMl allowed in abstract?

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/XML-mapping#8]
Does the PubMed conversion allow for this?

**Comment by Melissa37** [comment]
See https://github.com/elifesciences/XML-mapping/commit/81e04c2956aa81d9853b74fa080546078a0a1e10

**Comment by gnott** [comment]
I found one eLife article with mathml in the abstract: 10.7554/eLife.02043

Testing with that example, and refreshing my memory: when we parse the abstract from the XML for pubmed generation, all the inline-formula and/or mathml tags are removed entirely. The same goes for when figure captions are parsed, mathml is removed.

I created a test to include the mathml in the abstract. Although, it does not pass pubmed validation.

I think the suggested method (http://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.How_should_I_submit_mathem) is to replace the content with "[Formula: see text]". Currently this is replaced with no text at all.

We would also not include mathml in abstracts in the crossref deposits since they are stripped out upon parsing. I'm not sure if crossref supports them (it might).

**Comment by gnott** [comment]
To clarify, the tags are not entirely removed, but the content inside them is kept and the tags themselves are removed.

E.g.

```
scavenging, and
<inline-formula>
<mml:math id="inf1">
<mml:mrow>
<mml:msubsup>
<mml:mrow>
<mml:mtext>HCO</mml:mtext>
</mml:mrow>
<mml:mn>3</mml:mn>
<mml:mo>−</mml:mo>
</mml:msubsup>
</mml:mrow>
</mml:math>
</inline-formula>
transport
```

turns into

```
scavenging, and HCO3− transport
```

in the pubmed deposit abstract.

**Comment by Melissa37** [comment]
Ah, could be update the PubMed deposit to do as they suggest? This is low level requirement though as what we do is good enough I think.

**Comment by Melissa37** [comment]
CrossRef:

MathML may also be included using the 'mml' namespace prefix.
In face_markup group.

**Comment by gnott** [comment]
Re: pubmed, I think to follow the suggestion I would like to confirm the content is supplied in a suitable format.

"
`Simple formulas:`
- `Chemical - do not use <sup> or <inf> in chemical formulas, for example water should be submitted as H20, carbon dioxide as CO2.`
- `Mathematical - simple mathematical formulas should be submitted with the intended characters, e.g. x2.`

"
So the above example `<inline-formula>` could instead be (if I understand) replaced with something like

`HCO<sub>3</sub><sup>−</sup>`

Content in the XML aside, the fix would be to replace any <inline-formula> with "[Formula: see text]" when the pubmed deposit happens.

Re: crossref, if they support mml and we want to, then when the abstract is parsed from the XML during the pubmed/crossref process, we will need to retain the mml tags. But, when pubmed deposits happen, then the mml will get stripped out and replaced only on pubmed deposits. For crossref deposits we can convert the tags to the appropriate tags for crossref.

**Comment by gnott** [comment]
Will be continued in issue https://github.com/elifesciences/elife-pubmed-feed/issues/75 because PubMed supports some mathml now.
