### ISSUE TITLE
Is <inline-formula> @id attribute really not required?

### ISSUE THREAD

**Issue by gnott** [elifesciences/XML-mapping#89]
Hi @Melissa37,

I'm looking for content to add to the decision letter and author response to be more comprehensive. I notice in the `elife-00666.xml` kitchen sink XML, it says inside the `<inline-formula>` above the `<mml:math>` tag,

```
<!--  no id required for inline formulae  -->
```

In discussion with typesetters, it looks like if decision letter XML is generated, it is preferred for the `<mml:math>` tag to have an `@id` attribute.

I see in an example eLife XML file that the `<mml:math>` tags inside `<inline-formula>` also have an `@id` attribute in practice.

Is the `@id` attribute really not required, or has this become required over time? Even if not required, it looks like it may be important, and should the kitchen sink XML have `@id` attributes added to its `<mml:math>` tags?

**Comment by Melissa37** [comment]
Hi @gnott Thanks for pointing this out.
I 'think' we decided formual in the DL/AR did not need an ID because it would not be numbered and also because the sub article is separate form the main article. I also wondered whether we did not want the typesetting process to not confuse anything.

I defer to @JGilbert-eLife to remind us if there was a different reason!
I defer to @FAtherden-eLife as to what we should do going forward based on a good data model!

Thanks G, can we wait for the others to respond before making a decision? Also, might require discussion with Exeter as to why they do it.

**Comment by fred-atherden** [comment]
I don't think we expect to link to `inline-formula` (especially in the DL/AR) do we? If that's the case, then it's not necessary to include `@id` for that element. 

> I see in an example eLife XML file that the `<mml:math>` tags inside `<inline-formula>` also have an `@id` attribute in practice.

Yup, in the archive it looks like _every_ `mml:math` (which is a child of `inline-formula`) has an `@id` - there are none without!

> ... and should the kitchen sink XML have `@id` attributes added to its `<mml:math>` tags?

I don't see a problem with every `mml:math` having an `@id` - it's more consistent (although, again, not _necessary_ since they won't be linked to).

**Comment by Melissa37** [comment]
Hi there

Then I vote for adding to Kitchen sink. Thanks!

M

**Comment by gnott** [comment]
Thanks for the quick decision on the `@id` attribute. I will add them to the XML in the open PR.

**Comment by gnott** [comment]
@Melissa37, I agree with your point about how the numbering of maths `@id` when the decision letter is separate from the main article will probably happen. As long as the values are unique in an XML fragment, they can be renumbered later when combined. If following a sequential numbering in the `@id` of a generated decision letter gets to be problematic or confusing, we could possibly just assign them random values when the decision letter XML is generated.

**Comment by gnott** [comment]
I have no further questions about `@id` attributes on math formulae, so I will close this issue. Thanks again!
